import type { SkillMeta } from "../registry-types.js";

export const MEDIA_PROCESSING_SKILLS: SkillMeta[] = [
  {
    name: "audio-cleanup-lab",
    displayName: "Audio Cleanup Lab",
    description: "Professional audio cleanup recipes with structured workflows for processing audio files",
    category: "Media Processing",
    tags: ["audio", "cleanup", "processing", "restoration"],
  },
  {
    name: "audio-transcript-pack",
    displayName: "Audio Transcript Pack",
    description: "Generate hosted transcript packages with timestamps, summaries, show notes, clips, captions, and repurposing copy",
    category: "Media Processing",
    tags: ["audio", "transcript", "captions", "show-notes", "premium", "remote"],
  },
  {
    name: "compress-video",
    displayName: "Compress Video",
    description: "Compress video files while preserving visual quality using ffmpeg",
    category: "Media Processing",
    tags: ["video", "compression", "ffmpeg", "optimization"],
  },
  {
    name: "audio-extract",
    displayName: "Audio Extract",
    description: "Extract audio tracks from video files with multiple format support",
    category: "Media Processing",
    tags: ["audio", "extraction", "video", "conversion"],
  },
  {
    name: "extract-frames",
    displayName: "Extract Frames",
    description: "Extract frames from video files at specified intervals or timestamps",
    category: "Media Processing",
    tags: ["frames", "video", "extraction", "images"],
  },
  {
    name: "gif-maker",
    displayName: "GIF Maker",
    description: "Create animated GIFs from images, videos, or screen recordings",
    category: "Media Processing",
    tags: ["gif", "animation", "images", "video"],
  },
  {
    name: "highlight-reel-generator",
    displayName: "Highlight Reel Generator",
    description: "Generate video highlight reels from longer content with key moments",
    category: "Media Processing",
    tags: ["highlights", "video", "editing", "content"],
  },
  {
    name: "remove-background",
    displayName: "Remove Background",
    description: "Remove backgrounds from images using AI segmentation",
    category: "Media Processing",
    tags: ["background-removal", "image", "ai", "editing"],
  },
  {
    name: "subtitle",
    displayName: "Subtitle",
    description: "Generate styled subtitles from audio using OpenAI Whisper",
    category: "Media Processing",
    tags: ["subtitles", "transcription", "whisper", "video"],
  },
  {
    name: "transcript",
    displayName: "Transcript",
    description: "Transcribe audio, video, and media URLs with OpenAI GPT-4o, ElevenLabs Scribe v2, DeepGram, or hosted runtime",
    category: "Media Processing",
    tags: ["transcript", "audio", "video", "speech-to-text", "diarization", "youtube"],
  },
  {
    name: "video-cut-suggester",
    displayName: "Video Cut Suggester",
    description: "Suggest video cuts and edits based on content analysis and pacing",
    category: "Media Processing",
    tags: ["video", "editing", "cuts", "suggestions"],
  },
  {
    name: "video-highlight-pack",
    displayName: "Video Highlight Pack",
    description: "Generate hosted video highlight packages with clip plans, captions, thumbnail briefs, chapter markers, social posts, and edit decisions",
    category: "Media Processing",
    tags: ["video", "highlights", "clips", "captions", "premium", "remote"],
  },
  {
    name: "video-downloader",
    displayName: "Video Downloader",
    description: "Download videos from various online platforms and services",
    category: "Media Processing",
    tags: ["video", "download", "platforms", "media"],
  },
  {
    name: "video-thumbnail",
    displayName: "Video Thumbnail",
    description: "Generate eye-catching video thumbnails with text overlays",
    category: "Media Processing",
    tags: ["video", "thumbnail", "design", "youtube"],
  },
  {
    name: "watermark",
    displayName: "Watermark",
    description: "Add watermarks to images and documents for copyright protection",
    category: "Media Processing",
    tags: ["watermark", "protection", "copyright", "images"],
  },
];
